// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKYqC6tkI3OB--adta1AbdfaHQSwouJf4',
    appId: '1:1047828763517:web:2e50940414528ec2b9f214',
    messagingSenderId: '1047828763517',
    projectId: 'fire-gallery-4284d',
    authDomain: 'fire-gallery-4284d.firebaseapp.com',
    storageBucket: 'fire-gallery-4284d.appspot.com',
    measurementId: 'G-G47PXS4M6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_3XnBia1PM26cxXdOdtde8wqA2LVn10E',
    appId: '1:1047828763517:android:3beeac76f469dc9cb9f214',
    messagingSenderId: '1047828763517',
    projectId: 'fire-gallery-4284d',
    storageBucket: 'fire-gallery-4284d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhe4hCHKCRSnCBGLMyIQLcY9fGK1M_Nbc',
    appId: '1:1047828763517:ios:1ce902ee3e410038b9f214',
    messagingSenderId: '1047828763517',
    projectId: 'fire-gallery-4284d',
    storageBucket: 'fire-gallery-4284d.appspot.com',
    iosClientId: '1047828763517-nnd63e6npa0d9pnd84ionkg4n90a481g.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhe4hCHKCRSnCBGLMyIQLcY9fGK1M_Nbc',
    appId: '1:1047828763517:ios:1ce902ee3e410038b9f214',
    messagingSenderId: '1047828763517',
    projectId: 'fire-gallery-4284d',
    storageBucket: 'fire-gallery-4284d.appspot.com',
    iosClientId: '1047828763517-nnd63e6npa0d9pnd84ionkg4n90a481g.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireGallery',
  );
}
